var game = game || {};

var GPE_SETTINGS_SCREEN_WIDTH = 800;
var GPE_SETTINGS_SCREEN_HEIGHT = 480;
var GPE_SETTINGS_PROG_NAME = "Game";
var GPE_SETTINGS_VERSION_NUMBER = 1;
var GPE_MAX_OBJECT_TYPES = 3;
var GPE_SETTINGS_SYSTEM_OS  = "Browser";
var GPE_GAME_PUBLISHER = "PawByte";
var GPE_GAME_DEVELOPER = "PawByte DevHouse";
var GPE_GAME_OBJECTS_COUNT = 2;
var GPE_SETTINGS_IS_DEBUGGING = false;
var GPE_SETTINGS_SHOW_FPS = true;